from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
from launch.substitutions import PathJoinSubstitution


def generate_launch_description():
    config_file = PathJoinSubstitution([
        FindPackageShare('sentinel_lio'), 'config', 'sentinel_ouster.yaml'
    ])
    rviz_config_file = PathJoinSubstitution([
        FindPackageShare('sentinel_lio'), 'rviz_cfg', 'sentinel_mapping.rviz'
    ])

    return LaunchDescription([
        DeclareLaunchArgument('params_file', default_value=config_file),
        DeclareLaunchArgument('rviz', default_value='false'),
        DeclareLaunchArgument('rviz_config', default_value=rviz_config_file),
        DeclareLaunchArgument('enable_vfm', default_value='false'),
        DeclareLaunchArgument('enable_da3_depth', default_value='false'),
        DeclareLaunchArgument('enable_reflection_mask', default_value='false'),
        DeclareLaunchArgument('enable_mask_prior', default_value='false'),
        DeclareLaunchArgument('vfm_model_root', default_value=''),
        DeclareLaunchArgument('vfm_onnx_dir', default_value=''),
        DeclareLaunchArgument('left_topic', default_value='/zed2/zed_node/left/image_rect_color'),
        DeclareLaunchArgument('right_topic', default_value='/zed2/zed_node/right/image_rect_color'),
        DeclareLaunchArgument('depth_topic', default_value='/vfm/depth_image'),
        DeclareLaunchArgument('mask_topic', default_value='/vfm/mirror_mask'),
        DeclareLaunchArgument('mask_image_topic', default_value='/zed2/zed_node/left/image_rect_color'),
        DeclareLaunchArgument('mask_mode', default_value='none'),
        DeclareLaunchArgument('vfm_mask_mode', default_value='none'),
        DeclareLaunchArgument('mask_prior_mode', default_value=LaunchConfiguration('mask_mode')),
        DeclareLaunchArgument('mask_dir', default_value=''),
        DeclareLaunchArgument('mask_threshold', default_value='0.0'),
        DeclareLaunchArgument('mask_match_tolerance', default_value='0.05'),
        DeclareLaunchArgument('mask_prior_target_fps', default_value='10.0'),
        DeclareLaunchArgument('publish_empty_mask', default_value='true'),
        DeclareLaunchArgument('camera_fx', default_value='541.56'),
        DeclareLaunchArgument('baseline', default_value='0.12'),
        DeclareLaunchArgument('vfm_target_fps', default_value='10.0'),
        DeclareLaunchArgument('vfm_sync_queue_size', default_value='3'),
        DeclareLaunchArgument('vfm_stats_log_interval', default_value='5.0'),
        DeclareLaunchArgument('da3_backend', default_value='none'),
        DeclareLaunchArgument('da3_model', default_value=''),
        DeclareLaunchArgument('da3_checkpoint', default_value=''),
        DeclareLaunchArgument('da3_device', default_value='cuda'),
        DeclareLaunchArgument('da3_input_width', default_value='518'),
        DeclareLaunchArgument('da3_input_height', default_value='518'),
        DeclareLaunchArgument('da3_metric_scale', default_value='1.0'),
        DeclareLaunchArgument('da3_metric_shift', default_value='0.0'),
        DeclareLaunchArgument('da3_min_depth', default_value='0.05'),
        DeclareLaunchArgument('da3_max_depth', default_value='80.0'),
        DeclareLaunchArgument('reflection_mask_backend', default_value='torch'),
        DeclareLaunchArgument('reflection_mask_checkpoint', default_value=''),
        DeclareLaunchArgument('reflection_mask_device', default_value='cuda'),
        DeclareLaunchArgument('reflection_mask_width', default_value='512'),
        DeclareLaunchArgument('reflection_mask_height', default_value='288'),
        DeclareLaunchArgument('reflection_mask_threshold', default_value='0.5'),
        DeclareLaunchArgument('reflection_mask_target_fps', default_value='10.0'),
        DeclareLaunchArgument('reflection_mask_use_da3_prior', default_value='false'),
        DeclareLaunchArgument('reflection_mask_publish_prob', default_value='false'),
        Node(
            package='sentinel_lio',
            executable='fastlio_mapping',
            name='laserMapping',
            output='screen',
            parameters=[LaunchConfiguration('params_file')],
        ),
        Node(
            package='fast_foundation_stereo_ros',
            executable='vfm_stereo_node_wrapper.sh',
            name='vfm_stereo_trt_node',
            output='screen',
            condition=IfCondition(LaunchConfiguration('enable_vfm')),
            parameters=[{
                'model_root': LaunchConfiguration('vfm_model_root'),
                'onnx_dir': LaunchConfiguration('vfm_onnx_dir'),
                'left_topic': LaunchConfiguration('left_topic'),
                'right_topic': LaunchConfiguration('right_topic'),
                'depth_topic': LaunchConfiguration('depth_topic'),
                'mask_topic': LaunchConfiguration('mask_topic'),
                'mask_mode': LaunchConfiguration('vfm_mask_mode'),
                'mask_dir': LaunchConfiguration('mask_dir'),
                'mask_threshold': LaunchConfiguration('mask_threshold'),
                'mask_match_tolerance': LaunchConfiguration('mask_match_tolerance'),
                'publish_empty_mask': LaunchConfiguration('publish_empty_mask'),
                'camera_fx': LaunchConfiguration('camera_fx'),
                'baseline': LaunchConfiguration('baseline'),
                'target_fps': LaunchConfiguration('vfm_target_fps'),
                'sync_queue_size': LaunchConfiguration('vfm_sync_queue_size'),
                'stats_log_interval': LaunchConfiguration('vfm_stats_log_interval'),
            }],
        ),
        Node(
            package='fast_foundation_stereo_ros',
            executable='vfm_stereo_node_wrapper.sh',
            name='da3_depth_node',
            output='screen',
            condition=IfCondition(LaunchConfiguration('enable_da3_depth')),
            arguments=['da3_depth_node.py'],
            parameters=[{
                'image_topic': LaunchConfiguration('left_topic'),
                'depth_topic': LaunchConfiguration('depth_topic'),
                'target_fps': LaunchConfiguration('vfm_target_fps'),
                'stats_log_interval': LaunchConfiguration('vfm_stats_log_interval'),
                'da3_backend': LaunchConfiguration('da3_backend'),
                'da3_model': LaunchConfiguration('da3_model'),
                'da3_checkpoint': LaunchConfiguration('da3_checkpoint'),
                'da3_device': LaunchConfiguration('da3_device'),
                'da3_input_width': LaunchConfiguration('da3_input_width'),
                'da3_input_height': LaunchConfiguration('da3_input_height'),
                'da3_metric_scale': LaunchConfiguration('da3_metric_scale'),
                'da3_metric_shift': LaunchConfiguration('da3_metric_shift'),
                'da3_min_depth': LaunchConfiguration('da3_min_depth'),
                'da3_max_depth': LaunchConfiguration('da3_max_depth'),
            }],
        ),
        Node(
            package='fast_foundation_stereo_ros',
            executable='vfm_stereo_node_wrapper.sh',
            name='reflection_mask_node',
            output='screen',
            condition=IfCondition(LaunchConfiguration('enable_reflection_mask')),
            arguments=['reflection_mask_node.py'],
            parameters=[{
                'image_topic': LaunchConfiguration('left_topic'),
                'mask_topic': LaunchConfiguration('mask_topic'),
                'checkpoint': LaunchConfiguration('reflection_mask_checkpoint'),
                'backend': LaunchConfiguration('reflection_mask_backend'),
                'device': LaunchConfiguration('reflection_mask_device'),
                'target_fps': LaunchConfiguration('reflection_mask_target_fps'),
                'image_width': LaunchConfiguration('reflection_mask_width'),
                'image_height': LaunchConfiguration('reflection_mask_height'),
                'prob_threshold': LaunchConfiguration('reflection_mask_threshold'),
                'publish_prob': LaunchConfiguration('reflection_mask_publish_prob'),
                'use_da3_prior': LaunchConfiguration('reflection_mask_use_da3_prior'),
                'stats_log_interval': LaunchConfiguration('vfm_stats_log_interval'),
                'da3_backend': LaunchConfiguration('da3_backend'),
                'da3_model': LaunchConfiguration('da3_model'),
                'da3_checkpoint': LaunchConfiguration('da3_checkpoint'),
                'da3_device': LaunchConfiguration('da3_device'),
                'da3_input_width': LaunchConfiguration('da3_input_width'),
                'da3_input_height': LaunchConfiguration('da3_input_height'),
                'da3_metric_scale': LaunchConfiguration('da3_metric_scale'),
                'da3_metric_shift': LaunchConfiguration('da3_metric_shift'),
                'da3_min_depth': LaunchConfiguration('da3_min_depth'),
                'da3_max_depth': LaunchConfiguration('da3_max_depth'),
            }],
        ),
        Node(
            package='fast_foundation_stereo_ros',
            executable='mask_prior_node.py',
            name='reflection_mask_prior_node',
            output='screen',
            condition=IfCondition(LaunchConfiguration('enable_mask_prior')),
            parameters=[{
                'image_topic': LaunchConfiguration('mask_image_topic'),
                'mask_topic': LaunchConfiguration('mask_topic'),
                'mask_mode': LaunchConfiguration('mask_prior_mode'),
                'mask_dir': LaunchConfiguration('mask_dir'),
                'mask_threshold': LaunchConfiguration('mask_threshold'),
                'mask_match_tolerance': LaunchConfiguration('mask_match_tolerance'),
                'target_fps': LaunchConfiguration('mask_prior_target_fps'),
                'publish_empty_mask': LaunchConfiguration('publish_empty_mask'),
            }],
        ),
        Node(
            package='tf2_ros',
            executable='static_transform_publisher',
            name='world_to_camera_init',
            arguments=['0', '0', '0', '0', '0', '0', 'world', 'camera_init'],
        ),
        Node(
            package='rviz2',
            executable='rviz2',
            name='sentinel_mapping_rviz',
            output='screen',
            condition=IfCondition(LaunchConfiguration('rviz')),
            arguments=['-d', LaunchConfiguration('rviz_config')],
        ),
    ])
